logging:
  level:
    org.springframework.beans.factory: TRACE  # 打印Bean创建的每一步细节
    org.springframework.context: TRACE
server:
  port: 8082

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml  # 扫描resources/mapper目录下的所有XML文件
  type-aliases-package: com.yykl.order.model.entity  # 实体类别名包路径
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL驱动类
    url: jdbc:mysql://localhost:3306/yykl_order_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root  # 数据库用户名
    password: 123456  # 数据库密码
  data:
    redis:
      host: localhost  # Redis服务器地址
      port: 6379       # Redis端口，默认6379
      # 若Redis有密码或其他配置，补充如下
      # password: your_password
      # database: 0  # 数据库索引，默认0
      timeout: 3000ms # 连接超时时间
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  # Nacos服务器地址（需与你的Nacos部署地址一致）
        namespace: public  # 命名空间（默认public，若有自定义需对应）
        username: nacos
        password: nacos
  application:
    name: yykl-order-service  # 服务名（必须与你启动的服务名一致）
# 生产环境支付配置
payment:
  # 微信支付配置
  wechat:
    appId: wx1234567890abcdef  # 替换为实际AppID
    mchId: 1900000109          # 替换为实际商户号
    apiKey: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8  # 替换为实际API密钥
    certPath: classpath:cert/wechat/apiclient_cert.p12  # 证书路径（如有）

  # 支付宝配置
  alipay:
    appId: 2021003123456789    # 替换为实际AppID
    merchantPrivateKey: |      # 私钥（注意竖线保留换行）
      MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQ...
      ...（完整私钥内容）...
      +tO3jE1t5Q==
    alipayPublicKey: |         # 支付宝公钥（注意竖线保留换行）
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQE...
      ...（完整公钥内容）...
      QQIDAQAB
    notifyUrl: https://api.yourdomain.com/payment/alipay/notify  # 异步通知地址
    returnUrl: https://www.yourdomain.com/order/success          # 同步跳转地址